stages:
  - testing
  - qa
  - publish
  - docs

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_TAG != null || $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH)

variables:
  PIP_CACHE_DIR: "${CI_PROJECT_DIR}/.cache/pip"
  CONTAINER_TEST_IMAGE: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG
  CONTAINER_RELEASE_IMAGE: $CI_REGISTRY_IMAGE:latest

cache:
  key: "${CI_JOB_NAME}"
  paths:
    - .cache/pip

.testing-unit:
  stage: testing
  before_script:
    - pip install --upgrade pip
    - pip install jax[cpu]
    - pip install .[dev]
  script:
    - pytest -m "not slow"

testing-unit/3.10:
  extends: .testing-unit
  image: python:3.10
  coverage: '/^TOTAL.+?(\d+\%)$/'

testing-unit/3.11:
  extends: .testing-unit
  image: python:3.11

testing-unit/3.12:
  extends: .testing-unit
  image: python:3.12

pre-commits:
  stage: qa
  needs: []
  image: python:3.10
  before_script:
    - pip install pre-commit
    - pre-commit install
  script:
    - pre-commit run --all-files

ublish-release-package:
  stage: publish
  needs: []
  interruptible: true
  before_script:
    - pip install twine build setuptools_scm
  script:
    - python -m build
    - twine upload --username __token__ --password $PYPI_API_TOKEN dist/*.tar.gz dist/*.whl
  rules:
    - if: $CI_COMMIT_TAG =~ /^v\d+.\d+.\d+/
