repos:
- repo: https://github.com/asottile/pyupgrade
  rev: "v3.3.1"
  hooks:
  - id: pyupgrade
    args: ["--py310-plus"]

- repo: https://github.com/hadialqattan/pycln
  rev: "v2.1.3"
  hooks:
  - id: pycln
    args:
    - --all

- repo: https://github.com/PyCQA/isort
  rev: '5.12.0'
  hooks:
  - id: isort
    args:
    - --profile=black
    - --line-length=100

- repo: https://github.com/psf/black
  rev: '23.1.0'
  hooks:
  - id: black
    args:
    - --skip-string-normalization
    - --line-length=100

- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: 'v4.4.0'
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: double-quote-string-fixer
  - id: check-merge-conflict
  - id: debug-statements

- repo: https://github.com/pycqa/flake8
  rev: '6.0.0'
  hooks:
  - id: flake8
    name: flake 8 (src)
    args:
    - --max-line-length=100
    # E203 whitespace before ':' (black incompatibility)
    # E731 do not assign a lambda expression, use a def
    # F722 syntax error in forward annotation
    - --extend-ignore=E203,E731,F722
    files: ^astrosim/

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: 'v1.8.0'
  hooks:
  - id: mypy
    additional_dependencies:
    - healpy
    - jax
    - jaxtyping
    - jax_healpy
    - lineax
    - scipy
    args:
    - --strict
    - --show-error-codes
    - --enable-error-code=ignore-without-code
    files: ^astrosim/
