from functools import partial

import jax
import jax.numpy as jnp
from jaxtyping import Array, ArrayLike, Float, Key, PyTree

from furax import (
    AbstractLinearOperator,
    BlockDiagonalOperator,
    FourierOperator,
    MaskOperator,
    SymmetricBandToeplitzOperator,
    tree,
)
from furax.linalg import cg

from ._observation import HashedObservationMetadata

__all__ = [
    'gap_fill',
    'generate_noise_realization',
]


def gap_fill(
    key: Key[Array, ''],
    x: PyTree[Float[Array, ' *shape']],
    ninv: AbstractLinearOperator,
    mask: MaskOperator,
    *,
    rate: ArrayLike = 1.0,
    max_cg_steps: int = 50,
    rtol: float = 1e-4,
    atol: float = 0.0,
    preconditioner: AbstractLinearOperator | None = None,
    metadata: HashedObservationMetadata | None = None,
) -> PyTree[Float[Array, ' *shape']]:
    r"""Fill flagged time samples with a constrained noise realization, leaving good samples unchanged.

    Replaces each flagged sample with a draw from the noise model conditioned on the surrounding
    good data (a *constrained realization*), so the gap is filled consistently with the noise
    correlations rather than by interpolation. The fill is a free realization :math:`\xi` plus a
    correction that pins the good samples back to their data values:

    .. math::

        x_{\mathrm{fill}} = \xi + d, \quad
        d_{\mathrm{good}} = x_{\mathrm{good}} - \xi_{\mathrm{good}}, \quad
        (M_b\, N^{-1} M_b)\, d_{\mathrm{bad}} = -M_b\, N^{-1} d_{\mathrm{good}},

    where :math:`M_b` masks the flagged samples. Three things to note:

    - Good samples are returned bit-exact; only the gaps change.
    - The CG solve acts only on the flagged subspace.
    - :math:`\xi` is drawn from :math:`N`, obtained as the reciprocal of the inverse-noise PSD.

    The bare :math:`M_b N^{-1} M_b` system is ill-conditioned for correlated noise. Pass a
    ``preconditioner`` to fix this: the recommended choice is the flagged-block covariance
    :math:`M_b N M_b`, i.e. ``mask.complement() @ cov @ mask.complement()``, where ``cov`` is a cheap
    approximation of :math:`N` (its banded/Fourier form). Its product with the system operator
    differs from the identity only by a boundary term of rank :math:`\approx 2\times` (correlation
    bandwidth) :math:`\times` (number of gap edges): the coupling lives only within a bandwidth of
    each gap edge, so the rank is set by how many separate gaps there are, not by their width. CG
    then converges in roughly that many steps -- a handful for a few wide gaps, more for many
    fragmented ones, but far fewer than the unpreconditioned system in either case. The
    preconditioner must be symmetric positive definite and live in the flagged subspace (zero on the
    good samples).

    Args:
        key: A PRNG key generated by the user.
        x: The time-ordered vector to be filled.
        ninv: The inverse-noise operator :math:`N^{-1}`.
        mask: The good-sample mask :math:`M`; its zeros are the gaps.
        rate: The sampling rate of the data.
        max_cg_steps: Maximum number of CG steps for the flagged-subspace solve.
        rtol: Relative convergence tolerance for the solver.
        atol: Absolute convergence tolerance for the solver.
        preconditioner: Optional SPD preconditioner for the flagged-subspace CG (see above).
        metadata: Metadata folded into the random key for reproducibility.

    Returns:
        ``x`` with its flagged samples replaced by the constrained realization.

    Example:
        >>> key = jax.random.key(0)
        >>> ndet, nsamples = 3, 10
        >>> x = jax.random.normal(key, (ndet, nsamples))
        >>> in_structure = jax.ShapeDtypeStruct(x.shape, x.dtype)
        >>> good = jnp.broadcast_to(
        ...     jnp.array([1, 1, 1, 0, 0, 1, 1, 1, 1, 1], dtype=bool), x.shape
        ... )
        >>> mask = MaskOperator.from_boolean_mask(good, in_structure=in_structure)
        >>> ninv = SymmetricBandToeplitzOperator(jnp.array([1.0]), in_structure=in_structure)
        >>> cov = SymmetricBandToeplitzOperator(jnp.array([1.0]), in_structure=in_structure)  # N ≈ cov
        >>> preconditioner = (mask.complement() @ cov @ mask.complement()).reduce()
        >>> filled = gap_fill(key, x, ninv, mask, preconditioner=preconditioner)
        >>> assert jnp.all(filled[good] == x[good])
    """
    m = mask
    m_bad = m.complement()  # masks the flagged samples (gaps)
    # ξ ~ N, drawn from the reciprocal PSD of N⁻¹.
    xi = generate_noise_realization(key, ninv, rate, metadata=metadata, inverse=True)
    dg = m(tree.sub(x, xi))  # deviation on good samples, zero on the gaps
    # M_b N⁻¹ M_b is singular (zero on good) but SPD on the gaps; CG from zero stays on the gaps.
    a = m_bad @ ninv @ m_bad
    b = tree.mul(-1.0, m_bad(ninv(dg)))
    d_bad = cg(
        a,
        b,
        preconditioner=preconditioner,
        max_steps=max_cg_steps,
        rtol=rtol,
        atol=atol,
    ).solution
    # Keep good samples bit-exact; fill the gaps with ξ + d_bad
    return tree.add(m(x), m_bad(tree.add(xi, d_bad)))


@partial(jax.jit, static_argnames='inverse')
def generate_noise_realization(
    key: Key[Array, ''],
    cov: FourierOperator | SymmetricBandToeplitzOperator | BlockDiagonalOperator,
    fsamp: ArrayLike,
    metadata: HashedObservationMetadata | None = None,
    *,
    inverse: bool = False,
) -> PyTree[Float[Array, ' *shape']]:
    """Generates a Gaussian noise realization with the given covariance.

    Args:
        key: A PRNG key generated by the user.
        cov: The noise covariance operator (`N`), or -- with ``inverse=True`` -- the inverse-noise
            operator (`N⁻¹`), in which case the realization is drawn from the reciprocal PSD. The
            operator's structure is the output structure of this function.
        metadata: Metadata that are folded into the random key.
        fsamp: The sampling frequency of the data (recommended for correct normalization).
        inverse: If ``True``, ``cov`` is `N⁻¹` and the PSD is reciprocated before sampling.
    """
    # Pytree TODs: a block-diagonal operator gives one realization per block (fresh key each),
    # returned as a pytree matching its block structure. A bare operator gives a single leaf.
    if isinstance(cov, BlockDiagonalOperator):
        leaves, treedef = jax.tree.flatten(cov.blocks, is_leaf=_is_operator)
        keys = jax.tree.unflatten(treedef, list(jax.random.split(key, len(leaves))))
        return jax.tree.map(
            lambda blk, k: _draw_block(k, blk, fsamp, metadata, inverse=inverse),
            cov.blocks,
            keys,
            is_leaf=_is_operator,
        )

    return _draw_block(key, cov, fsamp, metadata, inverse=inverse)


def _is_operator(op: object) -> bool:
    return isinstance(op, AbstractLinearOperator)


def _get_kernel(n_tt: Float[Array, ' _'], size: int) -> Float[Array, ' {size}']:
    """Embed a one-sided autocorrelation band as the first column of a circulant matrix."""
    lagmax = n_tt.size - 1
    if size < 2 * lagmax + 1:
        msg = f'The maximum lag ({lagmax}) is too large for the required kernel size ({size}).'
        raise ValueError(msg)
    kernel = jnp.zeros(size, dtype=n_tt.dtype).at[: n_tt.size].set(n_tt)
    return kernel.at[size - lagmax :].set(n_tt[:0:-1])


@partial(jnp.vectorize, signature='(b)->(k)', excluded={1})
def _folded_psd(
    n_tt: Float[ArrayLike, ' _'], fft_size: int
) -> Float[Array, ' {fft_size // 2 + 1}']:
    """Returns the folded Power Spectral Density of a one-dimensional vector.

    Args:
        n_tt: The autocorrelation function of the vector.
        fft_size: The size of the FFT to use (at least twice the size of ``n_tt``).
    """
    n_tt = jnp.asarray(n_tt)
    kernel = _get_kernel(n_tt, fft_size)
    psd = jnp.abs(jnp.fft.rfft(kernel, n=fft_size))
    # zero out DC value
    psd = psd.at[0].set(0)
    return psd


def _draw_block(
    key: Key[Array, ''],
    cov: FourierOperator | SymmetricBandToeplitzOperator,
    fsamp: ArrayLike,
    metadata: HashedObservationMetadata | None = None,
    *,
    inverse: bool = False,
) -> Float[Array, ' *shape']:
    """Draw a noise realization for a single-leaf covariance (see :func:`generate_noise_realization`)."""
    structure = cov.in_structure

    # Split random key
    num = structure.shape[:-1]
    subkeys = jax.random.split(key, num) if metadata is None else metadata.split_key(key)
    if subkeys.shape != num:
        msg = (
            'Splitting key using provided metadata resulted in a wrong shape.'
            f'Expected {num}, got {subkeys.shape}.'
        )
        raise RuntimeError(msg)

    # Get the PSD values from the covariance matrix
    n = structure.shape[-1]
    if isinstance(cov, FourierOperator):
        fft_size = cov.fft_size
        psd = cov.get_kernel()
    elif isinstance(cov, SymmetricBandToeplitzOperator):
        fft_size = SymmetricBandToeplitzOperator._get_next_power_of_two(n)
        psd = _folded_psd(cov.band_values, fft_size)
    else:
        raise NotImplementedError(
            f'cov must be a FourierOperator or SymmetricBandToeplitzOperator, got {type(cov).__name__}'
        )

    # `inverse=True` means `cov` is N⁻¹: sample from the reciprocal PSD to draw from N.
    if inverse:
        psd = jnp.where(psd > 0, 1.0 / psd, 0.0)

    fsamp = jnp.asarray(fsamp)
    npsd = fft_size // 2 + 1
    if npsd != psd.shape[-1]:
        msg = f'PSD size {psd.shape[-1]} does not match expected size {npsd} for {fft_size=}.'
        raise ValueError(msg)

    @partial(jnp.vectorize, signature='(),(k)->(n)')
    def _draw(subkey, psd):  # type: ignore[no-untyped-def]
        # Gaussian Re/Im random numbers
        rngdata = jax.random.normal(subkey, shape=(fft_size,))

        # Set DC and Nyquist frequency imaginary parts to zero
        fdata = jnp.empty(npsd, dtype=complex)
        fdata = fdata.at[0].set(rngdata[0] + 0.0j)
        fdata = fdata.at[-1].set(rngdata[npsd - 1] + 0.0j)

        # Repack the other values
        fdata = fdata.at[1:-1].set(rngdata[1 : npsd - 1] + 1j * rngdata[-1 : npsd - 1 : -1])

        # Normalization factor
        norm = fsamp * float(npsd - 1) / 2

        # Scale by PSD and inverse FFT
        scale = jnp.sqrt(norm * psd)
        tdata = jnp.fft.irfft(fdata * scale, n=fft_size)

        # Extract the samples we want and remove DC level
        offset = (fft_size - n) // 2
        xi = tdata[offset : offset + n]
        return xi - jnp.mean(xi)

    return _draw(subkeys, psd)  # type: ignore[no-any-return]
