name: Build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
  release:
    types: [published]

jobs:

  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Build sdist
      run: pipx run build --sdist

    - uses: actions/upload-artifact@v3
      with:
        path: dist/*.tar.gz

  build_wheels:
    name: Build wheels (${{ matrix.python.version }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python:
          - version: "3.10"
            cp: cp310
          - version: "3.11"
            cp: cp311
          - version: "3.12"
            cp: cp312
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.22.0
        env:
          CIBW_BUILD: ${{ matrix.python.cp }}-*
#          CIBW_SKIP: "*-musllinux_*"
          CIBW_TEST_EXTRAS: dev
          CIBW_TEST_COMMAND: pytest # {package}/tests

      - uses: actions/upload-artifact@v4
        with:
          path: ./wheelhouse/*.whl

  upload_all:
    needs: [build_sdist, build_wheels]
    runs-on: ubuntu-latest
    if: github.event_name == 'release' && github.event.action == 'published'
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: artifact
          path: dist

      - uses: pypa/gh-action-pypi-publish@v1.5.1
        with:
          password: ${{ secrets.PYPI_SECRET }}
